[package]
name = "snips-nlu-ontology-rs"
version = "0.54.0"
authors = ["Adrien Ball <adrien.ball@snips.ai>"]

[dependencies]
libc = "0.2"
snips-nlu-ontology = { git = "https://github.com/snipsco/snips-nlu-ontology", tag = "0.54.0" }
snips-nlu-ontology-ffi-macros = { git = "https://github.com/snipsco/snips-nlu-ontology", tag = "0.54.0" }
snips-nlu-ontology-parsers-ffi-macros = { git = "https://github.com/snipsco/snips-nlu-ontology", tag = "0.54.0" }

[lib]
name = "snips_nlu_ontology_rs"
crate-type = ["cdylib"]
