[package]
name = "snips-nlu-ontology-doc"
version = "0.57.3"
authors = ["Adrien Ball <adrien.ball@snips.ai>"]

[build-dependencies]
snips-nlu-ontology = { path = "../snips-nlu-ontology" }
prettytable-rs = "0.6"
